Description: Pattern with packages for @DEVICE@ configurations
Name: jolla-configuration-@DEVICE@
Requires:
- pattern:jolla-hw-adaptation-@DEVICE@
- pattern:jolla-sailfish-applications
- pattern:jolla-ui-wayland
# Early stages of porting benefit from these:
- pattern:sailfish-porter-tools

Summary: Jolla Configuration @DEVICE@

