Description: Pattern with UI related packages for @DEVICE@ configurations
Name: jolla-ui-configuration-@DEVICE@
Requires:
- jolla-ambient-z@ICON_RES@
- ambient-icons-closed-z@ICON_RES@

# Introduced starting Sailfish OS 2.0.4.x:
# 3rd party accounts like Twitter, VK, cloud services, etc
- jolla-settings-accounts-extensions-3rd-party-all

Summary: Jolla UI Configuration @DEVICE@
